### ISSUE TITLE
detailed responses for cli utilities

### ISSUE THREAD

**Issue by km333** [claustres/quasar-feathers-tutorial#10]
Hi - not a big deal but quick to add in the readme - I think for completeness students would like to see which responses they should choose for the tutorial when running quasar/feathers cli commands
etc.

~/dev/quasar/pwa/api$ **feathers generate service**
? What kind of service is it? NeDB
? What is the name of the service? messages
? Which path should the service be registered on? /messages
? Does the service require authentication? Yes
? What is the database connection string? nedb://../data
    force config/default.json
   create src/services/messages/messages.service.js
    force src/services/index.js
   create src/models/messages.model.js
   create src/services/messages/messages.hooks.js
   create test/services/messages.test.js

**Comment by leob** [comment]
Good idea, added it to the README.
