### ISSUE TITLE
feathers-cli moved to @feathersjs/cli.

### ISSUE THREAD

**Issue by oger000** [claustres/quasar-feathers-tutorial#13]
Thanks for your great work.

FYI: 
> npm install -g feathers-cli
results in: Feathers v3 is out and this module has moved to `@feathersjs/cli.` See https://docs.feathersjs.com/migrating.html for more information.

should be now:
`npm install @feathersjs/cli -g`

**Comment by leob** [comment]
Right, so:

```npm install -g @feathersjs/cli```

**Comment by oger000** [comment]
Yes.
Needed some time to find how to write `"@feathersjs/cli"` in markdown ;-)

**Comment by leob** [comment]
Fixed the README, thanks for reporting this!
