### ISSUE TITLE
Page VS Component

### ISSUE THREAD

**Issue by etcogit** [claustres/quasar-feathers-tutorial#14]
Hi, Thanks for this tutorial !

I found some difference between the tutorial (wiki) and the source code.
In the tutorial, you put the code of the "Chat.vue" into src/**components**/Chat.vue.
But in the wiki, this code goes into /src/**pages**/Chat.vue

The component approach (like in the wiki) sounds me great but I don't know how to import the component into the /src/**pages**/Chat.vue.

Could you help me ? I searched on the internet how to create new components and import them into pages, but it's to difficult for me... So if you could explain how to procced it would be very useful for me ;-)

This is the same issue with the **SignIn.vue**

... and a happy New Year ;-)
Etienne

**Comment by leob** [comment]
Happy New Year as well!

This just looks like a typo to me ... I see that first the tutorial text talks about "src/components/Chat.vue", and then somewhere else it talks about "src/components/Chat.vue". However there is only one "Chat.vue", and it's found in the 'pages' directory.

The way it seems to be done in most Vue applications (at least the slightly more complex ones) is that there is a "pages" (or sometimes "views") directory that contains pages/views that are addressed via Vue-Router. The "components" directory contains 'smaller' components which are often reused in multiple pages.

What is the problem that you have when trying to load a 'component' within a 'page'?
Something like an "import" statement at the top of the 'script' section in your page, like this:

```
  import MyFancyButton from '../components/generic/MyFancyButton.vue'

  export default {
    components: {
       MyFancyButton
    },
```

Or am I misunderstanding your problem?

**Comment by claustres** [comment]
@leob Yes you are right, this tutorial is so simple that `views = pages = components` but usually a view/page can integrate many components by static import as you shown or dynamic loading provided by eg Webpack.

**Comment by etcogit** [comment]
OK. Thanks for answer...
What confused me is that I followed the text tutorial without cloning the project... (-> starting from scratch to learn more)
BUT the code in the text is not the same as in the project files.

But now I mixed both and it's working ;-)
