### ISSUE TITLE
feathers 2 generator error

### ISSUE THREAD

**Issue by dkebler** [claustres/quasar-feathers-tutorial#2]
First let me thank you profusely. About 6 months ago I was asking at the quasar forum about how to intergrate quasar with feathers.   Now you have done this excellent code/tutorial and it's a great jump off point for my project.    It will be great to build on your starting point and then make that available to the community.

A few things on the back end (api)

1. the new feathers client is not compatible with what you have done. 
Gives the following when running 

`feathers generate service`

```
✖ It does not look like this application has been generated with this version of the generator or the required `directories.lib` has been removed from package.json.
```
I guess I just start a new app and port over your code but you might want to do this yourself.  It runs as is but I can't add new services without doing this.

2.  The harmony flags inyour scripts throw errors and  aren't needed for node 7.8+

3.   I'd put the reference to the clilent config in the backend config file.   I moved your /api folder  to separate backend folder instead of a subfolder of the client and i had to track down that path and change it.

**Comment by claustres** [comment]
Hello, I am happy you use this work. Unfortunately I don't have much time in the next days to work on this, feel free to push any Pull Request.

I agree we should migrate to node 8 thus remove the harmony flag and probably change the babel preset.

We should also merge the template with an app generated with the last generator as you did.

If you'd like to see a deeper integration you might be interested by https://github.com/weacast/weacast a project started based on this template and some article I wrote for the FeathersJS blog:
- https://blog.feathersjs.com/feathersjs-in-production-configuration-api-prefixing-logging-and-error-catching-2a80e044e233
- https://blog.feathersjs.com/how-to-setup-oauth-flow-with-featherjs-522bdecb10a8

**Comment by dkebler** [comment]
Thanks,  your suggestions will keep me going for now.  As I go farther with your tutorial I'll be able do some PRs, but like u time is  limited. Probably not till Fall.  Still you have given me a great jumpstart with this repo as is.
