### ISSUE TITLE
Upgrade to Quasar v0.15

### ISSUE THREAD

**Issue by km333** [claustres/quasar-feathers-tutorial#8]

**Comment by leob** [comment]
Looks like a big upgrade ... @claustres you want me to take a shot at it?

**Comment by claustres** [comment]
Yes if you'd like you are also now owner of this project ;-). On my side I was waiting for v0.15 to stabilize until migrating my own projects (there has been something like 10 releases in the last month !).

**Comment by leob** [comment]
Sure, I'm also interested in it for an app that I'm developing ... I've read the change log, I'm impressed by the professionalism of the framework. Will have a look at the migration, I could write a followup 'migration' article on Medium.

**Comment by leob** [comment]
Need to work through this upgrade guide: http://quasar-framework.org/guide/quasar-upgrade-guide.html ... will have a look at it tomorrow.

**Comment by leob** [comment]
The upgrade is done, the app works successfully with Quasar 0.15.10 now.

I'm leaving the issue open because we still need to update the text of the tutorial (README.md file) - some of the Quasar/Vue code isn't correct anymore for Quasar 0.15.10.

**Comment by leob** [comment]
README updated, closing the issue now.

**Comment by claustres** [comment]
Great job
